NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca-orgG-example-com-7054-ca-orgG.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca-orgG-example-com-7054-ca-orgG.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/ca-orgG-example-com-7054-ca-orgG.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/ca-orgG-example-com-7054-ca-orgG.pem
    OrganizationalUnitIdentifier: orderer
