NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca-orgS-example-com-7054-ca-orgS.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca-orgS-example-com-7054-ca-orgS.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/ca-orgS-example-com-7054-ca-orgS.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/ca-orgS-example-com-7054-ca-orgS.pem
    OrganizationalUnitIdentifier: orderer
